DROP TABLE IF EXISTS users;
CREATE TABLE users (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name character varying(255) NOT NULL,
  age integer NOT NULL,
  Created date
) WITH (OIDS=FALSE);